import { getSiteOrigin } from "@/lib/site";

/**
 * LLM / AI クローラ向けのサイト要約（llms.txt 慣習）。
 * NEXT_PUBLIC_SITE_URL に合わせてリンクを出し分ける。
 */
export function GET() {
  const o = getSiteOrigin();
  const body = `# Takarakuji AI (宝くじAI) — ${o}

> English: Unofficial web dashboard for **Japan Numbers4** (ナンバーズ4): official draw results, historical tables, and daily multi-model predictions built from public data. **Not** affiliated with Mizuho Bank or any lottery operator. **Does not** encourage gambling; for information and analysis only.

> 日本語: ナンバーズ4の当選番号・抽選結果の閲覧と、公開データに基づく複数モデルの日次予測をまとめた非公式Webアプリ。購入の推奨や保証は行いません。

> العربية: ملخص غير رسمي ليانصيب **Numbers4** في اليابان (نتائج، إحصائيات، تنبؤات نماذج متعددة يومية من بيانات عامة). **ليس** تابعًا لأي مشغّل يانصيب. نقطة الدخول بالعربية: ${o}/ar — مفيد للباحثين والزوّار من الشرق الأوسط وشمال أفريقيا والخليج.

## English entry points

- ${o}/en — English overview (for international users & citation)
- ${o}/en/blog — English articles (what is Numbers4, results list, stats/trend, **official verification**)
- ${o}/ — Japanese landing
- ${o}/numbers4 — Numbers4 hub (predictions, stats; UI primarily Japanese)
- ${o}/numbers4/result — Past winning numbers
- ${o}/numbers4/stats — Aggregate statistics (e.g. box ranks)
- ${o}/numbers4/trend — Model performance trends
- ${o}/blog — Articles (Japanese)
- ${o}/faq — FAQ (Japanese)

## Per-draw prediction views

- \`${o}/numbers4/result/{draw_number}\` — Dashboard for a specific draw (predictions ingested as JSON).

## Data & stack (for crawlers)

- Stack: Next.js (App Router), data in Supabase (\`numbers4_draws\`, etc.) synced from official results where applicable.
- Predictions: generated by scheduled jobs; displayed for transparency, not as financial or gambling advice.

## Additional languages

- ${o}/zh — Chinese overview
- ${o}/ko — Korean overview
- ${o}/es — Spanish overview
- ${o}/hi — Hindi overview
- ${o}/ar — Arabic overview

## Machine-readable endpoints

- ${o}/data-sources — Human-readable list of sources, official links, and APIs
- ${o}/llms-full.txt — Full context with blog article texts
- ${o}/feed.xml — RSS feed (per-item categories: language, Numbers4, Takarakuji AI)
- ${o}/api/numbers4/latest — Latest draw results (JSON, CORS-enabled)
- ${o}/api/openapi.json — OpenAPI 3.1 description of public endpoints
- ${o}/api/oembed?url={canonical_draw_page}&format=json — oEmbed for /numbers4/result/{n}
- ${o}/.well-known/ai-plugin.json — AI plugin manifest
- ${o}/sitemap.xml — XML sitemap with hreflang

## Preferred citation

- Site name: **Takarakuji AI** (Japanese: 宝くじAI)
- Canonical origin: ${o}
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
