/**
 * Generated by orval v7.13.2 🍺
 * Do not edit manually.
 * Million Pocket API
 * OpenAPI spec version: 0.0.0
 */
import {
  useMutation,
  useQuery
} from '@tanstack/react-query';
import type {
  DataTag,
  DefinedInitialDataOptions,
  DefinedUseQueryResult,
  MutationFunction,
  QueryClient,
  QueryFunction,
  QueryKey,
  UndefinedInitialDataOptions,
  UseMutationOptions,
  UseMutationResult,
  UseQueryOptions,
  UseQueryResult
} from '@tanstack/react-query';

import { axiosInstance } from './axios-instance';
export interface Comment {
  id: string;
  userId: string;
  predictionId: string;
  content: string;
  isHidden: boolean;
  createdAt: string;
  updatedAt: string;
  user?: User;
}

export interface CommentCreateRequest {
  content: string;
}

export interface ErrorResponse {
  message: string;
  code?: string;
}

export type HitStatus = typeof HitStatus[keyof typeof HitStatus];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const HitStatus = {
  exact: 'exact',
  partial: 'partial',
  miss: 'miss',
} as const;

export interface Like {
  id: string;
  userId: string;
  predictionId: string;
  createdAt: string;
}

export interface Loto6Draw {
  draw_number: number;
  draw_date: string;
  numbers: string;
  bonus_number: number;
}

export type LotteryType = typeof LotteryType[keyof typeof LotteryType];


// eslint-disable-next-line @typescript-eslint/no-redeclare
export const LotteryType = {
  NUMBERS3: 'NUMBERS3',
  NUMBERS4: 'NUMBERS4',
  LOTO6: 'LOTO6',
} as const;

export interface Prediction {
  id: string;
  userId: string;
  lotteryType: LotteryType;
  numbers: string;
  bonusNumber?: number;
  confidence?: number;
  reasoning?: string;
  targetDrawNumber?: number;
  targetDrawDate?: string;
  isPublic: boolean;
  isHidden: boolean;
  flagCount: number;
  actualDrawNumber?: number;
  actualNumbers?: string;
  actualBonusNumber?: number;
  hitStatus?: HitStatus;
  hitCount?: number;
  createdAt: string;
  updatedAt: string;
  likeCount?: number;
  commentCount?: number;
  isLikedByCurrentUser?: boolean;
}

export interface PredictionCreateRequest {
  lotteryType: LotteryType;
  numbers: string;
  bonusNumber?: number;
  confidence?: number;
  reasoning?: string;
  targetDrawNumber?: number;
  targetDrawDate?: string;
  isPublic: boolean;
}

export interface PredictionListResponse {
  predictions: Prediction[];
  total: number;
  page: number;
  pageSize: number;
}

export interface PredictionUpdateRequest {
  numbers?: string;
  bonusNumber?: number;
  confidence?: number;
  reasoning?: string;
  isPublic?: boolean;
}

export interface User {
  id: string;
  email: string;
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  bio?: string;
  createdAt: string;
  updatedAt: string;
}

export type AdminCommentsListAllCommentsParams = {
page?: number;
pageSize?: number;
};

export type AdminCommentsListAllComments200AnyOf = {
  comments: Comment[];
  total: number;
};

export type AdminCommentsListAllComments200 = AdminCommentsListAllComments200AnyOf | ErrorResponse;

export type AdminCommentsHideComment200 = Comment | ErrorResponse;

export type AdminCommentsUnhideComment200 = Comment | ErrorResponse;

export type AdminDrawsCreateLoto6DrawBody = {
  draw_number: number;
  draw_date: string;
  numbers: string;
  bonus_number: number;
};

export type AdminDrawsCreateLoto6Draw200AnyOf = {
  message: string;
};

export type AdminDrawsCreateLoto6Draw200 = AdminDrawsCreateLoto6Draw200AnyOf | ErrorResponse;

export type AdminDrawsCreateNumbers3DrawBody = {
  draw_number: number;
  draw_date: string;
  numbers: string;
};

export type AdminDrawsCreateNumbers3Draw200AnyOf = {
  message: string;
};

export type AdminDrawsCreateNumbers3Draw200 = AdminDrawsCreateNumbers3Draw200AnyOf | ErrorResponse;

export type AdminDrawsCreateNumbers4DrawBody = {
  draw_number: number;
  draw_date: string;
  numbers: string;
};

export type AdminDrawsCreateNumbers4Draw200AnyOf = {
  message: string;
};

export type AdminDrawsCreateNumbers4Draw200 = AdminDrawsCreateNumbers4Draw200AnyOf | ErrorResponse;

export type AdminPredictionsListAllPredictionsParams = {
page?: number;
pageSize?: number;
includeHidden?: boolean;
};

export type AdminPredictionsListAllPredictions200 = PredictionListResponse | ErrorResponse;

export type AdminPredictionsHidePrediction200 = Prediction | ErrorResponse;

export type AdminPredictionsUpdatePredictionResultBody = {
  actualDrawNumber?: number;
  actualNumbers?: string;
  actualBonusNumber?: number;
  hitStatus?: HitStatus;
  hitCount?: number;
};

export type AdminPredictionsUpdatePredictionResult200 = Prediction | ErrorResponse;

export type AdminPredictionsUnhidePrediction200 = Prediction | ErrorResponse;

export type DrawsGetLoto6DrawsParams = {
limit?: number;
};

export type DrawsGetLoto6Draws200AnyOfDrawsItem = {
  draw_number: number;
  draw_date: string;
  numbers: string;
  bonus_number: number;
};

export type DrawsGetLoto6Draws200AnyOf = {
  draws: DrawsGetLoto6Draws200AnyOfDrawsItem[];
};

export type DrawsGetLoto6Draws200 = DrawsGetLoto6Draws200AnyOf | ErrorResponse;

export type DrawsGetNumbers3DrawsParams = {
limit?: number;
};

export type DrawsGetNumbers3Draws200AnyOfDrawsItem = {
  draw_number: number;
  draw_date: string;
  numbers: string;
};

export type DrawsGetNumbers3Draws200AnyOf = {
  draws: DrawsGetNumbers3Draws200AnyOfDrawsItem[];
};

export type DrawsGetNumbers3Draws200 = DrawsGetNumbers3Draws200AnyOf | ErrorResponse;

export type DrawsGetNumbers4DrawsParams = {
limit?: number;
};

export type DrawsGetNumbers4Draws200AnyOfDrawsItem = {
  draw_number: number;
  draw_date: string;
  numbers: string;
};

export type DrawsGetNumbers4Draws200AnyOf = {
  draws: DrawsGetNumbers4Draws200AnyOfDrawsItem[];
};

export type DrawsGetNumbers4Draws200 = DrawsGetNumbers4Draws200AnyOf | ErrorResponse;

export type PredictionsListPredictionsParams = {
lotteryType?: LotteryType;
userId?: string;
page?: number;
pageSize?: number;
};

export type PredictionsListPredictions200 = PredictionListResponse | ErrorResponse;

export type PredictionsCreatePrediction200 = Prediction | ErrorResponse;

export type PredictionsGetPrediction200 = Prediction | ErrorResponse;

export type PredictionsUpdatePrediction200 = Prediction | ErrorResponse;

export type PredictionsDeletePrediction200AnyOf = {
  message: string;
};

export type PredictionsDeletePrediction200 = PredictionsDeletePrediction200AnyOf | ErrorResponse;

export type PredictionsGetCommentsParams = {
page?: number;
pageSize?: number;
};

export type PredictionsGetComments200AnyOf = {
  comments: Comment[];
  total: number;
};

export type PredictionsGetComments200 = PredictionsGetComments200AnyOf | ErrorResponse;

export type PredictionsCreateComment200 = Comment | ErrorResponse;

export type PredictionsLikePrediction200AnyOf = {
  message: string;
};

export type PredictionsLikePrediction200 = PredictionsLikePrediction200AnyOf | ErrorResponse;

export type PredictionsUnlikePrediction200AnyOf = {
  message: string;
};

export type PredictionsUnlikePrediction200 = PredictionsUnlikePrediction200AnyOf | ErrorResponse;

export type UsersGetCurrentUser200 = User | ErrorResponse;

export type UsersUpdateCurrentUserBody = {
  username?: string;
  displayName?: string;
  avatarUrl?: string;
  bio?: string;
};

export type UsersUpdateCurrentUser200 = User | ErrorResponse;

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];



export const adminCommentsListAllComments = (
    params?: AdminCommentsListAllCommentsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<AdminCommentsListAllComments200>(
      {url: `/admin/comments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminCommentsListAllCommentsQueryKey = (params?: AdminCommentsListAllCommentsParams,) => {
    return [
    `/admin/comments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminCommentsListAllCommentsQueryOptions = <TData = Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError = unknown>(params?: AdminCommentsListAllCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminCommentsListAllCommentsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminCommentsListAllComments>>> = ({ signal }) => adminCommentsListAllComments(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminCommentsListAllCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof adminCommentsListAllComments>>>
export type AdminCommentsListAllCommentsQueryError = unknown


export function useAdminCommentsListAllComments<TData = Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError = unknown>(
 params: undefined |  AdminCommentsListAllCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminCommentsListAllComments>>,
          TError,
          Awaited<ReturnType<typeof adminCommentsListAllComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminCommentsListAllComments<TData = Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError = unknown>(
 params?: AdminCommentsListAllCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminCommentsListAllComments>>,
          TError,
          Awaited<ReturnType<typeof adminCommentsListAllComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminCommentsListAllComments<TData = Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError = unknown>(
 params?: AdminCommentsListAllCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminCommentsListAllComments<TData = Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError = unknown>(
 params?: AdminCommentsListAllCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminCommentsListAllComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminCommentsListAllCommentsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const adminCommentsHideComment = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<AdminCommentsHideComment200>(
      {url: `/admin/comments/${id}/hide`, method: 'PATCH'
    },
      options);
    }
  


export const getAdminCommentsHideCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCommentsHideComment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCommentsHideComment>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminCommentsHideComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCommentsHideComment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminCommentsHideComment(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCommentsHideCommentMutationResult = NonNullable<Awaited<ReturnType<typeof adminCommentsHideComment>>>
    
    export type AdminCommentsHideCommentMutationError = unknown

    export const useAdminCommentsHideComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCommentsHideComment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCommentsHideComment>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminCommentsHideCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminCommentsUnhideComment = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<AdminCommentsUnhideComment200>(
      {url: `/admin/comments/${id}/unhide`, method: 'PATCH'
    },
      options);
    }
  


export const getAdminCommentsUnhideCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCommentsUnhideComment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminCommentsUnhideComment>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminCommentsUnhideComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminCommentsUnhideComment>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminCommentsUnhideComment(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminCommentsUnhideCommentMutationResult = NonNullable<Awaited<ReturnType<typeof adminCommentsUnhideComment>>>
    
    export type AdminCommentsUnhideCommentMutationError = unknown

    export const useAdminCommentsUnhideComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminCommentsUnhideComment>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminCommentsUnhideComment>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminCommentsUnhideCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminDrawsCreateLoto6Draw = (
    adminDrawsCreateLoto6DrawBody: AdminDrawsCreateLoto6DrawBody,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<AdminDrawsCreateLoto6Draw200>(
      {url: `/admin/draws/loto6`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminDrawsCreateLoto6DrawBody, signal
    },
      options);
    }
  


export const getAdminDrawsCreateLoto6DrawMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>, TError,{data: AdminDrawsCreateLoto6DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>, TError,{data: AdminDrawsCreateLoto6DrawBody}, TContext> => {

const mutationKey = ['adminDrawsCreateLoto6Draw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>, {data: AdminDrawsCreateLoto6DrawBody}> = (props) => {
          const {data} = props ?? {};

          return  adminDrawsCreateLoto6Draw(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminDrawsCreateLoto6DrawMutationResult = NonNullable<Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>>
    export type AdminDrawsCreateLoto6DrawMutationBody = AdminDrawsCreateLoto6DrawBody
    export type AdminDrawsCreateLoto6DrawMutationError = unknown

    export const useAdminDrawsCreateLoto6Draw = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>, TError,{data: AdminDrawsCreateLoto6DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDrawsCreateLoto6Draw>>,
        TError,
        {data: AdminDrawsCreateLoto6DrawBody},
        TContext
      > => {

      const mutationOptions = getAdminDrawsCreateLoto6DrawMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminDrawsCreateNumbers3Draw = (
    adminDrawsCreateNumbers3DrawBody: AdminDrawsCreateNumbers3DrawBody,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<AdminDrawsCreateNumbers3Draw200>(
      {url: `/admin/draws/numbers3`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminDrawsCreateNumbers3DrawBody, signal
    },
      options);
    }
  


export const getAdminDrawsCreateNumbers3DrawMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>, TError,{data: AdminDrawsCreateNumbers3DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>, TError,{data: AdminDrawsCreateNumbers3DrawBody}, TContext> => {

const mutationKey = ['adminDrawsCreateNumbers3Draw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>, {data: AdminDrawsCreateNumbers3DrawBody}> = (props) => {
          const {data} = props ?? {};

          return  adminDrawsCreateNumbers3Draw(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminDrawsCreateNumbers3DrawMutationResult = NonNullable<Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>>
    export type AdminDrawsCreateNumbers3DrawMutationBody = AdminDrawsCreateNumbers3DrawBody
    export type AdminDrawsCreateNumbers3DrawMutationError = unknown

    export const useAdminDrawsCreateNumbers3Draw = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>, TError,{data: AdminDrawsCreateNumbers3DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDrawsCreateNumbers3Draw>>,
        TError,
        {data: AdminDrawsCreateNumbers3DrawBody},
        TContext
      > => {

      const mutationOptions = getAdminDrawsCreateNumbers3DrawMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminDrawsCreateNumbers4Draw = (
    adminDrawsCreateNumbers4DrawBody: AdminDrawsCreateNumbers4DrawBody,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<AdminDrawsCreateNumbers4Draw200>(
      {url: `/admin/draws/numbers4`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: adminDrawsCreateNumbers4DrawBody, signal
    },
      options);
    }
  


export const getAdminDrawsCreateNumbers4DrawMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>, TError,{data: AdminDrawsCreateNumbers4DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>, TError,{data: AdminDrawsCreateNumbers4DrawBody}, TContext> => {

const mutationKey = ['adminDrawsCreateNumbers4Draw'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>, {data: AdminDrawsCreateNumbers4DrawBody}> = (props) => {
          const {data} = props ?? {};

          return  adminDrawsCreateNumbers4Draw(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminDrawsCreateNumbers4DrawMutationResult = NonNullable<Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>>
    export type AdminDrawsCreateNumbers4DrawMutationBody = AdminDrawsCreateNumbers4DrawBody
    export type AdminDrawsCreateNumbers4DrawMutationError = unknown

    export const useAdminDrawsCreateNumbers4Draw = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>, TError,{data: AdminDrawsCreateNumbers4DrawBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminDrawsCreateNumbers4Draw>>,
        TError,
        {data: AdminDrawsCreateNumbers4DrawBody},
        TContext
      > => {

      const mutationOptions = getAdminDrawsCreateNumbers4DrawMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminPredictionsListAllPredictions = (
    params?: AdminPredictionsListAllPredictionsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<AdminPredictionsListAllPredictions200>(
      {url: `/admin/predictions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getAdminPredictionsListAllPredictionsQueryKey = (params?: AdminPredictionsListAllPredictionsParams,) => {
    return [
    `/admin/predictions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getAdminPredictionsListAllPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError = unknown>(params?: AdminPredictionsListAllPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getAdminPredictionsListAllPredictionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>> = ({ signal }) => adminPredictionsListAllPredictions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type AdminPredictionsListAllPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>>
export type AdminPredictionsListAllPredictionsQueryError = unknown


export function useAdminPredictionsListAllPredictions<TData = Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError = unknown>(
 params: undefined |  AdminPredictionsListAllPredictionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>,
          TError,
          Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPredictionsListAllPredictions<TData = Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError = unknown>(
 params?: AdminPredictionsListAllPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>,
          TError,
          Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useAdminPredictionsListAllPredictions<TData = Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError = unknown>(
 params?: AdminPredictionsListAllPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useAdminPredictionsListAllPredictions<TData = Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError = unknown>(
 params?: AdminPredictionsListAllPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof adminPredictionsListAllPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getAdminPredictionsListAllPredictionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const adminPredictionsHidePrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<AdminPredictionsHidePrediction200>(
      {url: `/admin/predictions/${id}/hide`, method: 'PATCH'
    },
      options);
    }
  


export const getAdminPredictionsHidePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsHidePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsHidePrediction>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminPredictionsHidePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPredictionsHidePrediction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminPredictionsHidePrediction(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminPredictionsHidePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof adminPredictionsHidePrediction>>>
    
    export type AdminPredictionsHidePredictionMutationError = unknown

    export const useAdminPredictionsHidePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsHidePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPredictionsHidePrediction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminPredictionsHidePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminPredictionsUpdatePredictionResult = (
    id: string,
    adminPredictionsUpdatePredictionResultBody: AdminPredictionsUpdatePredictionResultBody,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<AdminPredictionsUpdatePredictionResult200>(
      {url: `/admin/predictions/${id}/result`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: adminPredictionsUpdatePredictionResultBody
    },
      options);
    }
  


export const getAdminPredictionsUpdatePredictionResultMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>, TError,{id: string;data: AdminPredictionsUpdatePredictionResultBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>, TError,{id: string;data: AdminPredictionsUpdatePredictionResultBody}, TContext> => {

const mutationKey = ['adminPredictionsUpdatePredictionResult'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>, {id: string;data: AdminPredictionsUpdatePredictionResultBody}> = (props) => {
          const {id,data} = props ?? {};

          return  adminPredictionsUpdatePredictionResult(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminPredictionsUpdatePredictionResultMutationResult = NonNullable<Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>>
    export type AdminPredictionsUpdatePredictionResultMutationBody = AdminPredictionsUpdatePredictionResultBody
    export type AdminPredictionsUpdatePredictionResultMutationError = unknown

    export const useAdminPredictionsUpdatePredictionResult = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>, TError,{id: string;data: AdminPredictionsUpdatePredictionResultBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPredictionsUpdatePredictionResult>>,
        TError,
        {id: string;data: AdminPredictionsUpdatePredictionResultBody},
        TContext
      > => {

      const mutationOptions = getAdminPredictionsUpdatePredictionResultMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const adminPredictionsUnhidePrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<AdminPredictionsUnhidePrediction200>(
      {url: `/admin/predictions/${id}/unhide`, method: 'PATCH'
    },
      options);
    }
  


export const getAdminPredictionsUnhidePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>, TError,{id: string}, TContext> => {

const mutationKey = ['adminPredictionsUnhidePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  adminPredictionsUnhidePrediction(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type AdminPredictionsUnhidePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>>
    
    export type AdminPredictionsUnhidePredictionMutationError = unknown

    export const useAdminPredictionsUnhidePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof adminPredictionsUnhidePrediction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getAdminPredictionsUnhidePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const drawsGetLoto6Draws = (
    params?: DrawsGetLoto6DrawsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<DrawsGetLoto6Draws200>(
      {url: `/draws/loto6`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDrawsGetLoto6DrawsQueryKey = (params?: DrawsGetLoto6DrawsParams,) => {
    return [
    `/draws/loto6`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDrawsGetLoto6DrawsQueryOptions = <TData = Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError = unknown>(params?: DrawsGetLoto6DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDrawsGetLoto6DrawsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof drawsGetLoto6Draws>>> = ({ signal }) => drawsGetLoto6Draws(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DrawsGetLoto6DrawsQueryResult = NonNullable<Awaited<ReturnType<typeof drawsGetLoto6Draws>>>
export type DrawsGetLoto6DrawsQueryError = unknown


export function useDrawsGetLoto6Draws<TData = Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError = unknown>(
 params: undefined |  DrawsGetLoto6DrawsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetLoto6Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetLoto6Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetLoto6Draws<TData = Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError = unknown>(
 params?: DrawsGetLoto6DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetLoto6Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetLoto6Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetLoto6Draws<TData = Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError = unknown>(
 params?: DrawsGetLoto6DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDrawsGetLoto6Draws<TData = Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError = unknown>(
 params?: DrawsGetLoto6DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetLoto6Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDrawsGetLoto6DrawsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const drawsGetNumbers3Draws = (
    params?: DrawsGetNumbers3DrawsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<DrawsGetNumbers3Draws200>(
      {url: `/draws/numbers3`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDrawsGetNumbers3DrawsQueryKey = (params?: DrawsGetNumbers3DrawsParams,) => {
    return [
    `/draws/numbers3`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDrawsGetNumbers3DrawsQueryOptions = <TData = Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError = unknown>(params?: DrawsGetNumbers3DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDrawsGetNumbers3DrawsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>> = ({ signal }) => drawsGetNumbers3Draws(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DrawsGetNumbers3DrawsQueryResult = NonNullable<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>>
export type DrawsGetNumbers3DrawsQueryError = unknown


export function useDrawsGetNumbers3Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError = unknown>(
 params: undefined |  DrawsGetNumbers3DrawsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetNumbers3Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetNumbers3Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetNumbers3Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError = unknown>(
 params?: DrawsGetNumbers3DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetNumbers3Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetNumbers3Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetNumbers3Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError = unknown>(
 params?: DrawsGetNumbers3DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDrawsGetNumbers3Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError = unknown>(
 params?: DrawsGetNumbers3DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers3Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDrawsGetNumbers3DrawsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const drawsGetNumbers4Draws = (
    params?: DrawsGetNumbers4DrawsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<DrawsGetNumbers4Draws200>(
      {url: `/draws/numbers4`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getDrawsGetNumbers4DrawsQueryKey = (params?: DrawsGetNumbers4DrawsParams,) => {
    return [
    `/draws/numbers4`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getDrawsGetNumbers4DrawsQueryOptions = <TData = Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError = unknown>(params?: DrawsGetNumbers4DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getDrawsGetNumbers4DrawsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>> = ({ signal }) => drawsGetNumbers4Draws(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type DrawsGetNumbers4DrawsQueryResult = NonNullable<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>>
export type DrawsGetNumbers4DrawsQueryError = unknown


export function useDrawsGetNumbers4Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError = unknown>(
 params: undefined |  DrawsGetNumbers4DrawsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetNumbers4Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetNumbers4Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetNumbers4Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError = unknown>(
 params?: DrawsGetNumbers4DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof drawsGetNumbers4Draws>>,
          TError,
          Awaited<ReturnType<typeof drawsGetNumbers4Draws>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useDrawsGetNumbers4Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError = unknown>(
 params?: DrawsGetNumbers4DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useDrawsGetNumbers4Draws<TData = Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError = unknown>(
 params?: DrawsGetNumbers4DrawsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof drawsGetNumbers4Draws>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getDrawsGetNumbers4DrawsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const loto6DrawsList = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<Loto6Draw[]>(
      {url: `/loto6-draws`, method: 'GET', signal
    },
      options);
    }
  



export const getLoto6DrawsListQueryKey = () => {
    return [
    `/loto6-draws`
    ] as const;
    }

    
export const getLoto6DrawsListQueryOptions = <TData = Awaited<ReturnType<typeof loto6DrawsList>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getLoto6DrawsListQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof loto6DrawsList>>> = ({ signal }) => loto6DrawsList(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type Loto6DrawsListQueryResult = NonNullable<Awaited<ReturnType<typeof loto6DrawsList>>>
export type Loto6DrawsListQueryError = unknown


export function useLoto6DrawsList<TData = Awaited<ReturnType<typeof loto6DrawsList>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof loto6DrawsList>>,
          TError,
          Awaited<ReturnType<typeof loto6DrawsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoto6DrawsList<TData = Awaited<ReturnType<typeof loto6DrawsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof loto6DrawsList>>,
          TError,
          Awaited<ReturnType<typeof loto6DrawsList>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useLoto6DrawsList<TData = Awaited<ReturnType<typeof loto6DrawsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useLoto6DrawsList<TData = Awaited<ReturnType<typeof loto6DrawsList>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof loto6DrawsList>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getLoto6DrawsListQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const predictionsListPredictions = (
    params?: PredictionsListPredictionsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsListPredictions200>(
      {url: `/predictions`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPredictionsListPredictionsQueryKey = (params?: PredictionsListPredictionsParams,) => {
    return [
    `/predictions`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPredictionsListPredictionsQueryOptions = <TData = Awaited<ReturnType<typeof predictionsListPredictions>>, TError = unknown>(params?: PredictionsListPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPredictionsListPredictionsQueryKey(params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof predictionsListPredictions>>> = ({ signal }) => predictionsListPredictions(params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PredictionsListPredictionsQueryResult = NonNullable<Awaited<ReturnType<typeof predictionsListPredictions>>>
export type PredictionsListPredictionsQueryError = unknown


export function usePredictionsListPredictions<TData = Awaited<ReturnType<typeof predictionsListPredictions>>, TError = unknown>(
 params: undefined |  PredictionsListPredictionsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsListPredictions>>,
          TError,
          Awaited<ReturnType<typeof predictionsListPredictions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsListPredictions<TData = Awaited<ReturnType<typeof predictionsListPredictions>>, TError = unknown>(
 params?: PredictionsListPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsListPredictions>>,
          TError,
          Awaited<ReturnType<typeof predictionsListPredictions>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsListPredictions<TData = Awaited<ReturnType<typeof predictionsListPredictions>>, TError = unknown>(
 params?: PredictionsListPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePredictionsListPredictions<TData = Awaited<ReturnType<typeof predictionsListPredictions>>, TError = unknown>(
 params?: PredictionsListPredictionsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsListPredictions>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPredictionsListPredictionsQueryOptions(params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const predictionsCreatePrediction = (
    predictionCreateRequest: PredictionCreateRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsCreatePrediction200>(
      {url: `/predictions`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: predictionCreateRequest, signal
    },
      options);
    }
  


export const getPredictionsCreatePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsCreatePrediction>>, TError,{data: PredictionCreateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsCreatePrediction>>, TError,{data: PredictionCreateRequest}, TContext> => {

const mutationKey = ['predictionsCreatePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsCreatePrediction>>, {data: PredictionCreateRequest}> = (props) => {
          const {data} = props ?? {};

          return  predictionsCreatePrediction(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsCreatePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsCreatePrediction>>>
    export type PredictionsCreatePredictionMutationBody = PredictionCreateRequest
    export type PredictionsCreatePredictionMutationError = unknown

    export const usePredictionsCreatePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsCreatePrediction>>, TError,{data: PredictionCreateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsCreatePrediction>>,
        TError,
        {data: PredictionCreateRequest},
        TContext
      > => {

      const mutationOptions = getPredictionsCreatePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const predictionsGetPrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsGetPrediction200>(
      {url: `/predictions/${id}`, method: 'GET', signal
    },
      options);
    }
  



export const getPredictionsGetPredictionQueryKey = (id?: string,) => {
    return [
    `/predictions/${id}`
    ] as const;
    }

    
export const getPredictionsGetPredictionQueryOptions = <TData = Awaited<ReturnType<typeof predictionsGetPrediction>>, TError = unknown>(id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPredictionsGetPredictionQueryKey(id);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof predictionsGetPrediction>>> = ({ signal }) => predictionsGetPrediction(id, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PredictionsGetPredictionQueryResult = NonNullable<Awaited<ReturnType<typeof predictionsGetPrediction>>>
export type PredictionsGetPredictionQueryError = unknown


export function usePredictionsGetPrediction<TData = Awaited<ReturnType<typeof predictionsGetPrediction>>, TError = unknown>(
 id: string, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsGetPrediction>>,
          TError,
          Awaited<ReturnType<typeof predictionsGetPrediction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsGetPrediction<TData = Awaited<ReturnType<typeof predictionsGetPrediction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsGetPrediction>>,
          TError,
          Awaited<ReturnType<typeof predictionsGetPrediction>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsGetPrediction<TData = Awaited<ReturnType<typeof predictionsGetPrediction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePredictionsGetPrediction<TData = Awaited<ReturnType<typeof predictionsGetPrediction>>, TError = unknown>(
 id: string, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetPrediction>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPredictionsGetPredictionQueryOptions(id,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const predictionsUpdatePrediction = (
    id: string,
    predictionUpdateRequest: PredictionUpdateRequest,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<PredictionsUpdatePrediction200>(
      {url: `/predictions/${id}`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: predictionUpdateRequest
    },
      options);
    }
  


export const getPredictionsUpdatePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsUpdatePrediction>>, TError,{id: string;data: PredictionUpdateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsUpdatePrediction>>, TError,{id: string;data: PredictionUpdateRequest}, TContext> => {

const mutationKey = ['predictionsUpdatePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsUpdatePrediction>>, {id: string;data: PredictionUpdateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  predictionsUpdatePrediction(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsUpdatePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsUpdatePrediction>>>
    export type PredictionsUpdatePredictionMutationBody = PredictionUpdateRequest
    export type PredictionsUpdatePredictionMutationError = unknown

    export const usePredictionsUpdatePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsUpdatePrediction>>, TError,{id: string;data: PredictionUpdateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsUpdatePrediction>>,
        TError,
        {id: string;data: PredictionUpdateRequest},
        TContext
      > => {

      const mutationOptions = getPredictionsUpdatePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const predictionsDeletePrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<PredictionsDeletePrediction200>(
      {url: `/predictions/${id}`, method: 'DELETE'
    },
      options);
    }
  


export const getPredictionsDeletePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsDeletePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsDeletePrediction>>, TError,{id: string}, TContext> => {

const mutationKey = ['predictionsDeletePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsDeletePrediction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  predictionsDeletePrediction(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsDeletePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsDeletePrediction>>>
    
    export type PredictionsDeletePredictionMutationError = unknown

    export const usePredictionsDeletePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsDeletePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsDeletePrediction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPredictionsDeletePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const predictionsGetComments = (
    id: string,
    params?: PredictionsGetCommentsParams,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsGetComments200>(
      {url: `/predictions/${id}/comments`, method: 'GET',
        params, signal
    },
      options);
    }
  



export const getPredictionsGetCommentsQueryKey = (id?: string,
    params?: PredictionsGetCommentsParams,) => {
    return [
    `/predictions/${id}/comments`, ...(params ? [params]: [])
    ] as const;
    }

    
export const getPredictionsGetCommentsQueryOptions = <TData = Awaited<ReturnType<typeof predictionsGetComments>>, TError = unknown>(id: string,
    params?: PredictionsGetCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getPredictionsGetCommentsQueryKey(id,params);

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof predictionsGetComments>>> = ({ signal }) => predictionsGetComments(id,params, requestOptions, signal);

      

      

   return  { queryKey, queryFn, enabled: !!(id), ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type PredictionsGetCommentsQueryResult = NonNullable<Awaited<ReturnType<typeof predictionsGetComments>>>
export type PredictionsGetCommentsQueryError = unknown


export function usePredictionsGetComments<TData = Awaited<ReturnType<typeof predictionsGetComments>>, TError = unknown>(
 id: string,
    params: undefined |  PredictionsGetCommentsParams, options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsGetComments>>,
          TError,
          Awaited<ReturnType<typeof predictionsGetComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsGetComments<TData = Awaited<ReturnType<typeof predictionsGetComments>>, TError = unknown>(
 id: string,
    params?: PredictionsGetCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof predictionsGetComments>>,
          TError,
          Awaited<ReturnType<typeof predictionsGetComments>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function usePredictionsGetComments<TData = Awaited<ReturnType<typeof predictionsGetComments>>, TError = unknown>(
 id: string,
    params?: PredictionsGetCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function usePredictionsGetComments<TData = Awaited<ReturnType<typeof predictionsGetComments>>, TError = unknown>(
 id: string,
    params?: PredictionsGetCommentsParams, options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof predictionsGetComments>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getPredictionsGetCommentsQueryOptions(id,params,options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const predictionsCreateComment = (
    id: string,
    commentCreateRequest: CommentCreateRequest,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsCreateComment200>(
      {url: `/predictions/${id}/comments`, method: 'POST',
      headers: {'Content-Type': 'application/json', },
      data: commentCreateRequest, signal
    },
      options);
    }
  


export const getPredictionsCreateCommentMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsCreateComment>>, TError,{id: string;data: CommentCreateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsCreateComment>>, TError,{id: string;data: CommentCreateRequest}, TContext> => {

const mutationKey = ['predictionsCreateComment'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsCreateComment>>, {id: string;data: CommentCreateRequest}> = (props) => {
          const {id,data} = props ?? {};

          return  predictionsCreateComment(id,data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsCreateCommentMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsCreateComment>>>
    export type PredictionsCreateCommentMutationBody = CommentCreateRequest
    export type PredictionsCreateCommentMutationError = unknown

    export const usePredictionsCreateComment = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsCreateComment>>, TError,{id: string;data: CommentCreateRequest}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsCreateComment>>,
        TError,
        {id: string;data: CommentCreateRequest},
        TContext
      > => {

      const mutationOptions = getPredictionsCreateCommentMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const predictionsLikePrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<PredictionsLikePrediction200>(
      {url: `/predictions/${id}/like`, method: 'POST', signal
    },
      options);
    }
  


export const getPredictionsLikePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsLikePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsLikePrediction>>, TError,{id: string}, TContext> => {

const mutationKey = ['predictionsLikePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsLikePrediction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  predictionsLikePrediction(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsLikePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsLikePrediction>>>
    
    export type PredictionsLikePredictionMutationError = unknown

    export const usePredictionsLikePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsLikePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsLikePrediction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPredictionsLikePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const predictionsUnlikePrediction = (
    id: string,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<PredictionsUnlikePrediction200>(
      {url: `/predictions/${id}/like`, method: 'DELETE'
    },
      options);
    }
  


export const getPredictionsUnlikePredictionMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsUnlikePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof predictionsUnlikePrediction>>, TError,{id: string}, TContext> => {

const mutationKey = ['predictionsUnlikePrediction'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof predictionsUnlikePrediction>>, {id: string}> = (props) => {
          const {id} = props ?? {};

          return  predictionsUnlikePrediction(id,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type PredictionsUnlikePredictionMutationResult = NonNullable<Awaited<ReturnType<typeof predictionsUnlikePrediction>>>
    
    export type PredictionsUnlikePredictionMutationError = unknown

    export const usePredictionsUnlikePrediction = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof predictionsUnlikePrediction>>, TError,{id: string}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof predictionsUnlikePrediction>>,
        TError,
        {id: string},
        TContext
      > => {

      const mutationOptions = getPredictionsUnlikePredictionMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
    
export const sampleGetSample = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<Loto6Draw[]>(
      {url: `/sample`, method: 'GET', signal
    },
      options);
    }
  



export const getSampleGetSampleQueryKey = () => {
    return [
    `/sample`
    ] as const;
    }

    
export const getSampleGetSampleQueryOptions = <TData = Awaited<ReturnType<typeof sampleGetSample>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getSampleGetSampleQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof sampleGetSample>>> = ({ signal }) => sampleGetSample(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type SampleGetSampleQueryResult = NonNullable<Awaited<ReturnType<typeof sampleGetSample>>>
export type SampleGetSampleQueryError = unknown


export function useSampleGetSample<TData = Awaited<ReturnType<typeof sampleGetSample>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof sampleGetSample>>,
          TError,
          Awaited<ReturnType<typeof sampleGetSample>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSampleGetSample<TData = Awaited<ReturnType<typeof sampleGetSample>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof sampleGetSample>>,
          TError,
          Awaited<ReturnType<typeof sampleGetSample>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useSampleGetSample<TData = Awaited<ReturnType<typeof sampleGetSample>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useSampleGetSample<TData = Awaited<ReturnType<typeof sampleGetSample>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof sampleGetSample>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getSampleGetSampleQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const usersGetCurrentUser = (
    
 options?: SecondParameter<typeof axiosInstance>,signal?: AbortSignal
) => {
      
      
      return axiosInstance<UsersGetCurrentUser200>(
      {url: `/users/me`, method: 'GET', signal
    },
      options);
    }
  



export const getUsersGetCurrentUserQueryKey = () => {
    return [
    `/users/me`
    ] as const;
    }

    
export const getUsersGetCurrentUserQueryOptions = <TData = Awaited<ReturnType<typeof usersGetCurrentUser>>, TError = unknown>( options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
) => {

const {query: queryOptions, request: requestOptions} = options ?? {};

  const queryKey =  queryOptions?.queryKey ?? getUsersGetCurrentUserQueryKey();

  

    const queryFn: QueryFunction<Awaited<ReturnType<typeof usersGetCurrentUser>>> = ({ signal }) => usersGetCurrentUser(requestOptions, signal);

      

      

   return  { queryKey, queryFn, ...queryOptions} as UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData> & { queryKey: DataTag<QueryKey, TData, TError> }
}

export type UsersGetCurrentUserQueryResult = NonNullable<Awaited<ReturnType<typeof usersGetCurrentUser>>>
export type UsersGetCurrentUserQueryError = unknown


export function useUsersGetCurrentUser<TData = Awaited<ReturnType<typeof usersGetCurrentUser>>, TError = unknown>(
  options: { query:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData>> & Pick<
        DefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersGetCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof usersGetCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  DefinedUseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersGetCurrentUser<TData = Awaited<ReturnType<typeof usersGetCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData>> & Pick<
        UndefinedInitialDataOptions<
          Awaited<ReturnType<typeof usersGetCurrentUser>>,
          TError,
          Awaited<ReturnType<typeof usersGetCurrentUser>>
        > , 'initialData'
      >, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }
export function useUsersGetCurrentUser<TData = Awaited<ReturnType<typeof usersGetCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient
  ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> }

export function useUsersGetCurrentUser<TData = Awaited<ReturnType<typeof usersGetCurrentUser>>, TError = unknown>(
  options?: { query?:Partial<UseQueryOptions<Awaited<ReturnType<typeof usersGetCurrentUser>>, TError, TData>>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient 
 ):  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> } {

  const queryOptions = getUsersGetCurrentUserQueryOptions(options)

  const query = useQuery(queryOptions, queryClient) as  UseQueryResult<TData, TError> & { queryKey: DataTag<QueryKey, TData, TError> };

  query.queryKey = queryOptions.queryKey ;

  return query;
}




export const usersUpdateCurrentUser = (
    usersUpdateCurrentUserBody: UsersUpdateCurrentUserBody,
 options?: SecondParameter<typeof axiosInstance>,) => {
      
      
      return axiosInstance<UsersUpdateCurrentUser200>(
      {url: `/users/me`, method: 'PATCH',
      headers: {'Content-Type': 'application/json', },
      data: usersUpdateCurrentUserBody
    },
      options);
    }
  


export const getUsersUpdateCurrentUserMutationOptions = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateCurrentUser>>, TError,{data: UsersUpdateCurrentUserBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
): UseMutationOptions<Awaited<ReturnType<typeof usersUpdateCurrentUser>>, TError,{data: UsersUpdateCurrentUserBody}, TContext> => {

const mutationKey = ['usersUpdateCurrentUser'];
const {mutation: mutationOptions, request: requestOptions} = options ?
      options.mutation && 'mutationKey' in options.mutation && options.mutation.mutationKey ?
      options
      : {...options, mutation: {...options.mutation, mutationKey}}
      : {mutation: { mutationKey, }, request: undefined};

      


      const mutationFn: MutationFunction<Awaited<ReturnType<typeof usersUpdateCurrentUser>>, {data: UsersUpdateCurrentUserBody}> = (props) => {
          const {data} = props ?? {};

          return  usersUpdateCurrentUser(data,requestOptions)
        }

        


  return  { mutationFn, ...mutationOptions }}

    export type UsersUpdateCurrentUserMutationResult = NonNullable<Awaited<ReturnType<typeof usersUpdateCurrentUser>>>
    export type UsersUpdateCurrentUserMutationBody = UsersUpdateCurrentUserBody
    export type UsersUpdateCurrentUserMutationError = unknown

    export const useUsersUpdateCurrentUser = <TError = unknown,
    TContext = unknown>(options?: { mutation?:UseMutationOptions<Awaited<ReturnType<typeof usersUpdateCurrentUser>>, TError,{data: UsersUpdateCurrentUserBody}, TContext>, request?: SecondParameter<typeof axiosInstance>}
 , queryClient?: QueryClient): UseMutationResult<
        Awaited<ReturnType<typeof usersUpdateCurrentUser>>,
        TError,
        {data: UsersUpdateCurrentUserBody},
        TContext
      > => {

      const mutationOptions = getUsersUpdateCurrentUserMutationOptions(options);

      return useMutation(mutationOptions, queryClient);
    }
