/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/auth/signup": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 新規ユーザー登録
         * @description メールアドレス、パスワード、ユーザー名で新規ユーザーを登録します
         */
        post: operations["signup"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * ログイン
         * @description メールアドレスとパスワードでログインします
         */
        post: operations["login"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 抽選情報一覧取得
         * @description 抽選情報の一覧をページネーション付きで取得します
         */
        get: operations["getDraws"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/upcoming": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 開催予定の抽選情報取得
         * @description 今後開催予定の抽選情報を取得します
         */
        get: operations["getUpcomingDraws"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/draws/{drawId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 特定の抽選情報取得
         * @description IDで指定した抽選情報を取得します
         */
        get: operations["getDrawById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 予測投稿一覧取得
         * @description 予測投稿の一覧をページネーション付きで取得します
         */
        get: operations["getPredictionPosts"];
        put?: never;
        /**
         * 新しい予測を投稿
         * @description 特定の抽選回に対する予測を投稿します
         */
        post: operations["createPredictionPost"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{postId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * 特定の予測投稿取得
         * @description IDで指定した予測投稿を取得します
         */
        get: operations["getPredictionPostById"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{postId}/likes": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * 投稿に「いいね」する
         * @description 特定の予測投稿に「いいね」を追加します
         */
        post: operations["likePredictionPost"];
        /**
         * 「いいね」を取り消す
         * @description 特定の予測投稿の「いいね」を取り消します
         */
        delete: operations["unlikePredictionPost"];
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/predictions/{postId}/comments": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * コメントを投稿する
         * @description 特定の予測投稿にコメントを追加します
         */
        post: operations["createComment"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザープロフィール取得
         * @description 特定のユーザーの公開プロフィールを取得します
         */
        get: operations["getUserProfile"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/predictions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーの予測投稿一覧取得
         * @description 特定のユーザーの予測投稿履歴を取得します
         */
        get: operations["getUserPredictionPosts"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/users/{userId}/analysis": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * ユーザーの予測成績分析取得
         * @description 特定のユーザーの宝くじ種類別予測成績を分析した結果を取得します
         */
        get: operations["getUserPredictionAnalysis"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        User: {
            /**
             * Format: uuid
             * @description ユーザーID（Supabase auth.users.idと一致）
             */
            id: string;
            /**
             * Format: email
             * @description メールアドレス
             */
            email: string;
            /** @description ユーザー名 */
            username?: string | null;
            /** @description 表示名 */
            displayName?: string | null;
            /**
             * Format: uri
             * @description アバター画像URL
             */
            avatarUrl?: string | null;
            /** @description 自己紹介 */
            bio?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt?: string;
        };
        AuthResponse: {
            /** @description Supabaseセッション情報 */
            session?: {
                access_token?: string;
                refresh_token?: string;
                expires_in?: number;
                token_type?: string;
            } | null;
            user?: components["schemas"]["User"];
        };
        Error: {
            /**
             * @description エラーメッセージ
             * @example Invalid request body
             */
            error: string;
        };
        /**
         * @description 宝くじの種類
         * @enum {string}
         */
        LotteryType: "NUMBERS3" | "NUMBERS4" | "LOTO6" | "BINGO5" | "LOTO7" | "MINILOTO";
        Pagination: {
            /** @description ページ内のアイテム */
            items: unknown[];
            /**
             * @description 総件数
             * @example 150
             */
            total: number;
            /**
             * @description 現在のページ番号
             * @example 1
             */
            page: number;
            /**
             * @description 1ページあたりの件数
             * @example 20
             */
            limit: number;
        };
        Draw: {
            /** @description 抽選ID */
            id: string;
            lotteryType: components["schemas"]["LotteryType"];
            /**
             * @description 回号
             * @example 1850
             */
            drawNumber: number;
            /**
             * Format: date-time
             * @description 抽選日時
             */
            drawDate: string;
            /**
             * @description 当選番号（結果発表後に設定）
             * @example 1,10,22,33,40,41
             */
            winningNumbers?: string | null;
            /**
             * Format: date-time
             * @description 作成日時
             */
            createdAt?: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt?: string;
        };
        Prediction: {
            /** @description 予測ID */
            id: string;
            /** @description 予測投稿ID */
            predictionPostId: string;
            /** @description 予測した数字（宝くじ種類により形式が異なる） */
            numbers: {
                /**
                 * @example [
                 *       1,
                 *       10,
                 *       22,
                 *       33,
                 *       40,
                 *       41
                 *     ]
                 */
                numbers?: number[];
            } | {
                /** @example 1234 */
                numbers?: string;
            };
        };
        PredictionPost: {
            /** @description 予測投稿ID */
            id: string;
            /** @description 投稿したユーザーID */
            userId: string;
            /** @description 対象の抽選ID */
            drawId: string;
            /**
             * Format: date-time
             * @description 投稿日時
             */
            createdAt: string;
            user?: components["schemas"]["User"];
            draw?: components["schemas"]["Draw"];
            /** @description この投稿に含まれる予測（最大5つ） */
            predictions?: components["schemas"]["Prediction"][];
            /** @description いいね数 */
            likesCount?: number;
            /** @description コメント数 */
            commentsCount?: number;
        };
        Like: {
            /** @description いいねID */
            id: string;
            /** @description いいねしたユーザーID */
            userId: string;
            /** @description いいね対象の投稿ID */
            predictionPostId: string;
            /**
             * Format: date-time
             * @description いいね日時
             */
            createdAt: string;
        };
        Comment: {
            /** @description コメントID */
            id: string;
            /** @description コメントしたユーザーID */
            userId: string;
            /** @description コメント対象の投稿ID */
            predictionPostId: string;
            /** @description コメント内容 */
            content: string;
            /**
             * @description 非表示フラグ
             * @default false
             */
            isHidden: boolean;
            /**
             * Format: date-time
             * @description コメント日時
             */
            createdAt: string;
            /**
             * Format: date-time
             * @description 更新日時
             */
            updatedAt?: string;
        };
        LotteryAnalysis: {
            /**
             * @description 総予測数
             * @example 50
             */
            totalPredictions?: number;
            /**
             * @description 当選数
             * @example 5
             */
            totalWins?: number;
            /**
             * Format: float
             * @description 的中率
             * @example 0.1
             */
            winRate?: number;
            /** @description 詳細内訳（将来拡張用） */
            breakdown?: Record<string, never>[];
        };
        UserAnalysis: {
            /** @description ユーザーID */
            userId: string;
            /** @description ユーザー名 */
            username: string;
            /** @description 宝くじ種類別の予測成績分析 */
            analysis: {
                loto6?: components["schemas"]["LotteryAnalysis"];
                numbers4?: components["schemas"]["LotteryAnalysis"];
                numbers3?: components["schemas"]["LotteryAnalysis"];
            };
        };
    };
    responses: {
        /** @description リソースが見つかりません */
        NotFound: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リクエストが不正です */
        BadRequest: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証が必要です */
        Unauthorized: {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リクエストが不正です */
        "responses-BadRequest": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description 認証が必要です */
        "responses-Unauthorized": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
        /** @description リソースが見つかりません */
        "responses-NotFound": {
            headers: {
                [name: string]: unknown;
            };
            content: {
                "application/json": components["schemas"]["Error"];
            };
        };
    };
    parameters: {
        /** @description ページ番号（1始まり） */
        PageParam: number;
        /** @description 1ページあたりの件数 */
        LimitParam: number;
        /** @description ユーザーID */
        UserIdPath: string;
        /** @description 抽選ID */
        DrawIdPath: string;
        /** @description 予測投稿ID */
        PostIdPath: string;
    };
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    signup: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description メールアドレス
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description パスワード（6文字以上）
                     * @example password123
                     */
                    password: string;
                    /**
                     * @description ユーザー名
                     * @example testuser
                     */
                    username: string;
                };
            };
        };
        responses: {
            /** @description 登録成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            400: components["responses"]["responses-BadRequest"];
        };
    };
    login: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /**
                     * Format: email
                     * @description メールアドレス
                     * @example user@example.com
                     */
                    email: string;
                    /**
                     * @description パスワード
                     * @example password123
                     */
                    password: string;
                };
            };
        };
        responses: {
            /** @description ログイン成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AuthResponse"];
                };
            };
            401: components["responses"]["responses-Unauthorized"];
        };
    };
    getDraws: {
        parameters: {
            query?: {
                /** @description 宝くじの種類でフィルタ */
                lotteryType?: components["schemas"]["LotteryType"];
                /** @description ページ番号（1始まり） */
                page?: components["parameters"]["PageParam"];
                /** @description 1ページあたりの件数 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items?: components["schemas"]["Draw"][];
                    };
                };
            };
        };
    };
    getUpcomingDraws: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draw"][];
                };
            };
        };
    };
    getDrawById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 抽選ID */
                drawId: components["parameters"]["DrawIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Draw"];
                };
            };
            404: components["responses"]["responses-NotFound"];
        };
    };
    getPredictionPosts: {
        parameters: {
            query?: {
                /** @description ページ番号（1始まり） */
                page?: components["parameters"]["PageParam"];
                /** @description 1ページあたりの件数 */
                limit?: components["parameters"]["LimitParam"];
                /** @description ユーザーIDでフィルタ */
                userId?: string;
                /** @description 抽選IDでフィルタ */
                drawId?: string;
                /** @description 宝くじの種類でフィルタ */
                lotteryType?: components["schemas"]["LotteryType"];
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items?: components["schemas"]["PredictionPost"][];
                    };
                };
            };
        };
    };
    createPredictionPost: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ユーザーID（将来は認証トークンから取得） */
                    userId: string;
                    /** @description 対象の抽選ID */
                    drawId: string;
                    predictions: {
                        numbers?: number[] | string;
                    }[];
                };
            };
        };
        responses: {
            /** @description 投稿成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionPost"];
                };
            };
            400: components["responses"]["responses-BadRequest"];
        };
    };
    getPredictionPostById: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予測投稿ID */
                postId: components["parameters"]["PostIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PredictionPost"];
                };
            };
            404: components["responses"]["responses-NotFound"];
        };
    };
    likePredictionPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予測投稿ID */
                postId: components["parameters"]["PostIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ユーザーID（将来は認証トークンから取得） */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description いいね成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Like"];
                };
            };
            400: components["responses"]["responses-BadRequest"];
        };
    };
    unlikePredictionPost: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予測投稿ID */
                postId: components["parameters"]["PostIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ユーザーID（将来は認証トークンから取得） */
                    userId: string;
                };
            };
        };
        responses: {
            /** @description 取り消し成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        /** @example true */
                        success?: boolean;
                    };
                };
            };
        };
    };
    createComment: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description 予測投稿ID */
                postId: components["parameters"]["PostIdPath"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": {
                    /** @description ユーザーID（将来は認証トークンから取得） */
                    userId: string;
                    /**
                     * @description コメント内容
                     * @example すごい予測ですね！
                     */
                    content: string;
                };
            };
        };
        responses: {
            /** @description コメント投稿成功 */
            201: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Comment"];
                };
            };
            400: components["responses"]["responses-BadRequest"];
        };
    };
    getUserProfile: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["User"];
                };
            };
            404: components["responses"]["responses-NotFound"];
        };
    };
    getUserPredictionPosts: {
        parameters: {
            query?: {
                /** @description ページ番号（1始まり） */
                page?: components["parameters"]["PageParam"];
                /** @description 1ページあたりの件数 */
                limit?: components["parameters"]["LimitParam"];
            };
            header?: never;
            path: {
                /** @description ユーザーID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Pagination"] & {
                        items?: components["schemas"]["PredictionPost"][];
                    };
                };
            };
        };
    };
    getUserPredictionAnalysis: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description ユーザーID */
                userId: components["parameters"]["UserIdPath"];
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description 成功 */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["UserAnalysis"];
                };
            };
            404: components["responses"]["responses-NotFound"];
        };
    };
}
