import { blogPosts } from "@/lib/blog/posts";
import { blogPostsEn } from "@/lib/blog/posts-en";
import { getSiteOrigin } from "@/lib/site";

/**
 * llms-full.txt — 詳細版のAI/LLMクローラ向けサイト要約。
 * llms.txt が要約版、こちらはブログ記事の全文を含むフルバージョン。
 */
export function GET() {
  const o = getSiteOrigin();

  const jaArticles = blogPosts
    .map(
      (p) => `### ${p.title}
URL: ${o}/blog/${p.slug}
Published: ${p.publishedAt}

${p.bodyMarkdown}`,
    )
    .join("\n\n---\n\n");

  const enArticles = blogPostsEn
    .map(
      (p) => `### ${p.title}
URL: ${o}/en/blog/${p.slug}
Published: ${p.publishedAt}

${p.bodyMarkdown}`,
    )
    .join("\n\n---\n\n");

  const body = `# Takarakuji AI (宝くじAI) — Full Context for LLMs
# Canonical origin: ${o}

> This is the **full version** of the site summary for AI systems.
> For the short version, see ${o}/llms.txt

## Site overview

Takarakuji AI is an **unofficial** web dashboard for Japan's Numbers4 (ナンバーズ4) lottery. It provides:

1. **Draw results** — Historical winning numbers from official public data (${o}/numbers4/result)
2. **Multi-model predictions** — Daily predictions from multiple ML/statistical models (${o}/numbers4)
3. **Box rank statistics** — Aggregate analysis of prediction accuracy (${o}/numbers4/stats)
4. **Hot model trends** — Short-term model performance comparison (${o}/numbers4/trend)
5. **Blog** — Guides in Japanese (${o}/blog) and English (${o}/en/blog)
6. **FAQ** — Frequently asked questions (${o}/faq)

## Important disclaimers

- **NOT** affiliated with Mizuho Bank, the Japan Lottery, or any official operator
- Predictions are experimental and based on public historical data
- Content is for research and entertainment only, not financial or gambling advice
- Always verify results with official sources

## Available languages

- Japanese (primary): ${o}/
- English: ${o}/en
- Chinese: ${o}/zh
- Korean: ${o}/ko
- Spanish: ${o}/es
- Hindi: ${o}/hi
- Arabic: ${o}/ar

## Arabic overview (ملخص بالعربية)

> **تاكاراكوجي AI** — موقع وتحليلات **غير رسمية** ليانصيب **Numbers4** في اليابان: قوائم نتائج السحب العلنية، إحصائيات واتجاهات، وتنبؤات يومية من عدة نماذج (بيانات تاريخية عامة). **ليس** تابعًا لميزوهو بنك أو أي مشغّل يانصيب رسمي. التنبؤات للبحث والاطلاع فقط وليست نصيحة مالية أو مقامرة.
>
> **نقطة الدخول بالعربية:** ${o}/ar
>
> **روابط مفيدة (واجهة يابانية أساسًا):** ${o}/numbers4 — ${o}/numbers4/result — ${o}/numbers4/stats — ${o}/numbers4/trend

## Technical stack

- Framework: Next.js (App Router)
- Database: Supabase (tables: numbers4_draws, numbers4_daily_prediction_documents, etc.)
- Predictions: generated by scheduled Python jobs, stored as JSON
- Hosting: Vercel

## API endpoints

- ${o}/api/numbers4/latest — Latest draw results and predictions (JSON)
- ${o}/feed.xml — RSS feed of blog articles
- ${o}/sitemap.xml — XML sitemap with hreflang
- ${o}/llms.txt — Short LLM summary
- ${o}/llms-full.txt — This file (full context)

## Per-draw prediction views

URL pattern: ${o}/numbers4/result/{draw_number}
Each page shows predictions from multiple models alongside official results (when available).

---

## Japanese blog articles (full text)

${jaArticles}

---

## English blog articles (full text)

${enArticles}

---

## Preferred citation

- Site name: **Takarakuji AI** (Japanese: 宝くじAI)
- Canonical origin: ${o}
- Contact: See site footer
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
