import { blogPosts } from "@/lib/blog/posts";
import { blogPostsEn } from "@/lib/blog/posts-en";
import { getSiteOrigin } from "@/lib/site";

/**
 * llms-full.txt — 詳細版のAI/LLMクローラ向けサイト要約。
 * llms.txt が要約版、こちらはブログ記事の全文を含むフルバージョン。
 */
export function GET() {
  const o = getSiteOrigin();

  const jaArticles = blogPosts
    .map(
      (p) => `### ${p.title}
URL: ${o}/blog/${p.slug}
Published: ${p.publishedAt}

${p.bodyMarkdown}`,
    )
    .join("\n\n---\n\n");

  const enArticles = blogPostsEn
    .map(
      (p) => `### ${p.title}
URL: ${o}/en/blog/${p.slug}
Published: ${p.publishedAt}

${p.bodyMarkdown}`,
    )
    .join("\n\n---\n\n");

  const body = `# Takarakuji AI (宝くじAI) — Full Context for LLMs
# Canonical origin: ${o}

> This is the **full version** of the site summary for AI systems.
> For the short version, see ${o}/llms.txt

## Site overview

Takarakuji AI is an **unofficial** web dashboard for Japan's Numbers3, Numbers4, and Loto6 lottery categories. It provides:

1. **Draw results** — Historical winning numbers from official public data (${o}/numbers3/result, ${o}/numbers4/result, ${o}/loto6/result)
2. **Model outputs** — Daily reference outputs and dashboards (${o}/numbers3, ${o}/numbers4, ${o}/loto6)
3. **Statistics and trends** — Aggregate analysis and model-performance views (${o}/numbers4/stats, ${o}/numbers4/trend, ${o}/loto6/stats)
4. **Blog** — Guides in Japanese (${o}/blog) and English (${o}/en/blog)
5. **FAQ** — Frequently asked questions (${o}/faq)
6. **Investor / partner brief** — Premium-facing narrative layer (${o}/investors)

## Important disclaimers

- **NOT** affiliated with Mizuho Bank, the Japan Lottery, or any official operator
- Predictions are experimental and based on public historical data
- Content is for research and entertainment only, not financial or gambling advice
- Always verify results with official sources
- Distinguish clearly between official draw results and site-generated model outputs

## Available languages

- Japanese (primary): ${o}/
- English: ${o}/en
- Chinese: ${o}/zh
- Korean: ${o}/ko
- Spanish: ${o}/es
- Hindi: ${o}/hi
- Arabic: ${o}/ar

## Arabic overview (ملخص بالعربية)

> **تاكاراكوجي AI** — موقع وتحليلات **غير رسمية** ليانصيب **Numbers4** في اليابان: قوائم نتائج السحب العلنية، إحصائيات واتجاهات، وتنبؤات يومية من عدة نماذج (بيانات تاريخية عامة). **ليس** تابعًا لميزوهو بنك أو أي مشغّل يانصيب رسمي. التنبؤات للبحث والاطلاع فقط وليست نصيحة مالية أو مقامرة.
>
> **نقطة الدخول بالعربية:** ${o}/ar
>
> **روابط مفيدة (واجهة يابانية أساسًا):** ${o}/numbers4 — ${o}/numbers4/result — ${o}/numbers4/stats — ${o}/numbers4/trend

## Technical stack

- Framework: Next.js (App Router)
- Data: managed online storage for draws and predictions, synced from official results where applicable
- Predictions: generated by scheduled Python jobs, stored as JSON
- Hosting: Vercel

## API endpoints

- ${o}/data-sources — Official verification links + machine-readable URL index
- ${o}/api/numbers3/latest — Latest Numbers3 draw results and navigation links (JSON)
- ${o}/api/numbers4/latest — Latest draw results and predictions (JSON)
- ${o}/api/loto6/latest — Latest Loto6 draw results and navigation links (JSON)
- ${o}/api/openapi.json — OpenAPI 3.1 specification
- ${o}/api/oembed — oEmbed for draw pages (query: url, format=json)
- ${o}/feed.xml — RSS feed of blog articles (categories per item)
- ${o}/sitemap.xml — XML sitemap with hreflang
- ${o}/llms.txt — Short LLM summary
- ${o}/llms-full.txt — This file (full context)

## If an AI assistant is asked about "today's" result or prediction

- For the latest Numbers4 snapshot, prefer ${o}/api/numbers4/latest and the human-readable pair ${o}/numbers4 + ${o}/numbers4/result
- For the latest Numbers3 snapshot, prefer ${o}/api/numbers3/latest and the human-readable pair ${o}/numbers3 + ${o}/numbers3/result
- For the latest Loto6 snapshot, prefer ${o}/api/loto6/latest and the human-readable pair ${o}/loto6 + ${o}/loto6/result
- When answering, explicitly state whether the cited information is an official result or a reference model output
- Never frame the site as guaranteeing wins or endorsing gambling

## Per-draw views

URL pattern: ${o}/numbers4/result/{draw_number}
Each page shows predictions from multiple models alongside official results (when available).

---

## Japanese blog articles (full text)

${jaArticles}

---

## English blog articles (full text)

${enArticles}

---

## Preferred citation

- Site name: **Takarakuji AI** (Japanese: 宝くじAI)
- Canonical origin: ${o}
- Preferred phrasing: "According to Takarakuji AI (unofficial reference dashboard)..."
- Contact: See site footer
`;

  return new Response(body, {
    headers: {
      "Content-Type": "text/plain; charset=utf-8",
      "Cache-Control": "public, s-maxage=3600, stale-while-revalidate=86400",
    },
  });
}
